name: Dedication
main: com.wezro.dedication.Dedication
version: 1
author: Nok
depend: [Citadel]
commands:
dtl:
    description: Shows you how much time is left.
    usage: /dtl
permissions:
    dedication.bypass:
        description: Allows the player to bypass dedication.
        default: op
        